#!/system/bin/sh

# LG Optimus 2X TweakAIO SysFS interface OverClock management init script v1.0.1
# Copyright (c) by vadonka 2012

#### if you want to use custom range and volts then set this to yes
custom="no"
# if you want to use custom range you can adjust the freq and voltage levels here.
# accepted freq values: 216000 312000 324000 456000 503000 608000 760000 816000 912000 1000000 1100000 1216000 1408000"
# volt range: 775-1250
#
# example:
custom_freq_range="216000 312000 456000 608000 760000 816000 912000 1000000"
custom_volt_range="775 800 825 850 875 900 950 975"
custom_min_freq="216000"
custom_max_freq="1000000"
####

date=`date +%Y.%m.%d-%H.%M.%S`
deflog="/data/tweakaio/logs/tweakaio.log"
parfile="/data/tweakaio/tweakaio.conf"

pfsize=`ls -la $parfile | awk -F " " '{print $5}'`
if [ -f $parfile ]; then
	if [ "$pfsize" == "0" ]; then
		echo "$date ERROR: Config file invalid" >> $deflog
		exit 0
	fi
fi

OCLEVEL=`grep "^OverClock Level" $parfile | awk -F "=" '{ print $2 }'`

if [ "$custom" != "yes" ]; then
	if [ "$OCLEVEL" == "stock" ]; then
		echo "$date OC Level: Stock, max CPU Freq Set to 1000000" >> $deflog
		echo "216000 324000 456000 608000 760000 816000 912000 1000000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
		echo "216000 324000 456000 608000 760000 816000 912000 1000000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_step_freqs
		echo "775 800 825 850 875 900 950 975" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_step_volts
		echo 216000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
		echo 1000000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	elif [ "$OCLEVEL" == "loc" ]; then
		echo "$date OC Level: Light, max CPU Freq Set to 1216000" >> $deflog
		echo "216000 324000 456000 608000 816000 1000000 1100000 1216000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
		echo "216000 324000 456000 608000 816000 1000000 1100000 1216000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_step_freqs
		echo "775 800 825 850 900 975 1050 1150" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_step_volts
		echo 216000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
		echo 1216000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	elif [ "$OCLEVEL" == "hoc" ]; then
		echo "$date OC Level: High, max CPU Freq Set to 1408000" >> $deflog
		echo "216000 324000 503000 816000 1000000 1100000 1216000 1408000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
		echo "216000 324000 503000 816000 1000000 1100000 1216000 1408000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_step_freqs
		echo "775 800 850 900 975 1050 1150 1250" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_step_volts
		echo 216000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
		echo 1408000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	else
		echo "$date OC level: High, max CPU Freq Set to 1408000" >> $deflog
	fi
elif [ "$custom" == "yes" ]; then
	echo "$date OC Level: Custom, max CPU Freq Set to $custom_max_freq" >> $deflog
	echo "$custom_freq_range" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
	echo "$custom_freq_range" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_step_freqs
	echo "$custom_volt_range" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_step_volts
	echo $custom_min_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
	echo $custom_max_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
fi
